package me.mrarcane.crispycore.managers;

import me.mrarcane.crispycore.utils.FileUtil;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;
import org.bukkit.scheduler.BukkitTask;

import java.util.List;
import java.util.Random;

import static me.mrarcane.crispycore.Main.announcer;
import static me.mrarcane.crispycore.utils.ChatUtil.log;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 1/9/2018
 **/
public class AnnouncementManager {

    public static BukkitTask broadcast(Plugin plugin) {
        FileUtil cfg = new FileUtil(null, "Announcements");
        List<String> msgs = cfg.getStringList("Messages");
        long interval = cfg.getLong("Options.Interval");
        long time = interval * 1200; //This allows it to go through every 1 minute.
        Random r = new Random();
        return Bukkit.getScheduler().runTaskTimerAsynchronously(plugin, () -> {
            if (Bukkit.getOnlinePlayers().size() < 1) { //Be smart and shut her down :)
                log("There are no players online, shutting down broadcaster to reduce console spam.");
                announcer.cancel();
                return;
            }
            if (msgs.size() < 1) {
                announcer.cancel();
                return;
            }
            for (Player p : Bukkit.getOnlinePlayers()) {
                sendChat(p, msgs.get(r.nextInt(msgs.size())));
            }
        }, time, time);
    }

    public static void restart(Plugin plugin) {
        announcer.cancel();
        announcer = broadcast(plugin);
    }
}