package me.mrarcane.crispycore.managers;

import me.mrarcane.crispycore.Main;
import org.bukkit.Material;
import org.bukkit.configuration.Configuration;
import org.bukkit.entity.Arrow;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockIgniteEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityDamageByEntityEvent;
import org.bukkit.event.entity.EntityShootBowEvent;
import org.bukkit.event.player.PlayerBucketFillEvent;
import org.bukkit.event.player.PlayerFishEvent;
import org.bukkit.event.player.PlayerShearEntityEvent;
import org.bukkit.inventory.ItemStack;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;
import static org.bukkit.event.block.BlockIgniteEvent.IgniteCause;

/**
 * File generated by: MrArcane
 * 3/15/2019
 **/
public class AprilFoolsManager implements Listener {

    private Configuration cfg = Main.getInstance().getConfig();

    public boolean isSword(ItemStack is) {
        return is.getType().name().contains("SWORD");
    }

    @EventHandler
    private void onPlace(BlockPlaceEvent e) {
        if (cfg.getBoolean("April fools")) {
            if (e.getBlock().getType() == Material.TORCH) {
                sendChat(e.getPlayer(), "&cWHAT ARE YOU DOING?!?");
            }
        }
    }

    @EventHandler
    private void onShoot(EntityShootBowEvent e) {
        if (cfg.getBoolean("April fools")) {
            if (e.getEntity() instanceof Player && e.getProjectile() instanceof Arrow) {
                Player p = (Player) e.getEntity();
                sendChat(p, "&4Pew!");
            }
        }
    }

    @EventHandler
    public void onShear(PlayerShearEntityEvent e) {
        if (cfg.getBoolean("April fools")) {
            Player p = e.getPlayer();
            sendChat(p, "&4Snip snip");
        }
    }

    @EventHandler
    private void onBite(PlayerFishEvent e) {
        if (cfg.getBoolean("April fools")) {
            if (e.getState() == PlayerFishEvent.State.BITE) {
                sendChat(e.getPlayer(), "&4You've got a big one!");
            }
        }
    }

    @EventHandler
    private void bucket(PlayerBucketFillEvent e) {
        if (cfg.getBoolean("April fools")) {
            sendChat(e.getPlayer(), "&4Scoop!");
        }
    }

    @EventHandler
    private void onDamage(EntityDamageByEntityEvent e) {
        if (cfg.getBoolean("April fools")) {
            if (e.getDamager() instanceof Player) {
                Player p = (Player) e.getDamager();
                if (isSword(p.getItemInHand())) {
                    sendChat(p, "&4Swoop!");
                }
            }
        }
    }

    @EventHandler
    private void onBurn(BlockIgniteEvent e) {
        if (cfg.getBoolean("April fools")) {
            if (e.getCause() == IgniteCause.FLINT_AND_STEEL) {
                sendChat(e.getPlayer(), "&4Burn baby burn!");
            }
        }
    }
}
