package me.mrarcane.crispycore.managers;

import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

/**
 * File generated by: MrArcane
 * 3/11/2019
 **/
public class TabCompleteManager implements TabCompleter {

    public List<String> onTabComplete(CommandSender sender, Command cmd, String commandLabel, String[] args) {
        List<String> result = new ArrayList<>();
        Player p = (Player) sender;
        //Home command
        PlayerManager user = new PlayerManager(p.getUniqueId().toString());
        Set<String> homeSection = user.getConfigurationSection("Home data").getKeys(false);
        List<String> homeNames = new ArrayList<>();
        if (cmd.getName().equalsIgnoreCase("home") && homeSection.size() == 0) {
            return Collections.singletonList("You don't have any homes!");
        } else if (cmd.getName().equalsIgnoreCase("home")) {
            for (String name : homeSection) {
                homeNames.add(name);
            }
            return homeNames;
        }
        //Home teleport
        if (cmd.getName().equalsIgnoreCase("hometeleport")) {
            List<String> players = new ArrayList<>();
            List<String> homeNames2 = new ArrayList<>();
            for (Player player : Bukkit.getOnlinePlayers()) {
                players.add(player.getName());
            }
            if (args.length <= 1) {
                return players;
            }
            OfflinePlayer player = Bukkit.getOfflinePlayer(args[0]);
            PlayerManager user2 = new PlayerManager(player.getUniqueId().toString());
            for (String name : user2.getConfigurationSection("Home data").getKeys(false)) {
                homeNames2.add(name);
            }
            if (user2.getConfigurationSection("Home data").getKeys(false).size() == 0) {
                return Collections.singletonList(player.getName() + " doesn't have any homes!");
            }
            return homeNames2;
        }
        if (cmd.getName().equalsIgnoreCase("funitem")) {
            List<String> name = new ArrayList<>();
            if (args.length == 1) {
                name.add("Trout");
                name.add("Stick");
            }
            return name;
        }
       /* TEMPLATE if (cmd.getName().equalsIgnoreCase("")) {
            return;
        }*/

        return result;
    }
}
