package me.mrarcane.crispycore.listeners;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.utils.PlayerUtil;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.EnderDragon;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.EntityDeathEvent;
import org.bukkit.event.entity.PlayerDeathEvent;
import org.bukkit.event.player.PlayerRespawnEvent;
import org.bukkit.inventory.ItemStack;

import java.util.List;
import java.util.Objects;
import java.util.Random;

import static me.mrarcane.crispycore.commands.SuicideCommand.suicide;
import static me.mrarcane.crispycore.utils.ChatUtil.color;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/8/2018
 **/
public class DeathListener implements Listener {

    @EventHandler
    public static void onPlayerDeath(PlayerDeathEvent e) {
        FileConfiguration cfg = Main.getInstance().getConfig();
        Player p = e.getEntity();
        PlayerUtil user = new PlayerUtil(p.getUniqueId().toString());
        int x = p.getLocation().getBlockX();
        int y = p.getLocation().getBlockY();
        int z = p.getLocation().getBlockZ();
        if (suicide.containsKey(p)) {
            e.setDeathMessage(color(String.format("&c%s has committed suicide.", p.getName())));
            suicide.remove(p);
            return;
        }
        if (p.hasPermission("crispycore.perks.death")) {
            sendChat(p, "&eYour death coordinates have been mailed to you.");
            List<String> m = Objects.requireNonNull(user.getConfigurationSection("Player")).getStringList("Mail");
            m.add(String.format("&4DEATH: &4X: &7%s &4Y: &7%s &4Z: &7%s", x, y, z));
            user.getConfigurationSection("Player").set("Mail", m);
            user.save();
        }
    }
    @EventHandler
    public static void onRespawn(PlayerRespawnEvent e) {
        FileConfiguration cfg = Main.getInstance().getConfig();
        if (!e.isBedSpawn()) {
            ConfigurationSection s = cfg.getConfigurationSection("Spawn");
            if (cfg.getConfigurationSection("Spawn") != null) {
                e.setRespawnLocation(new Location(Bukkit.getWorld(s.getString("w")), s.getDouble("x"), s.getDouble("y"), s.getDouble("z")));
            }
        }
    }
    @EventHandler
    public static void onMobDeath(EntityDeathEvent event) {
        Random r = new Random();
        Random r2 = new Random();
        Random r3 = new Random();
        Player p = event.getEntity().getKiller();
        int e = r.nextInt(4);
        int s = r2.nextInt(100);
        int d = r3.nextInt(500);
        if (event.getEntity() instanceof EnderDragon) {
            if (e == 2) {
               p.getInventory().addItem(new ItemStack(Material.ELYTRA));
                sendChat(p, "&eAn elytra has appeared in your inventory.");
            }
            if (s == 27) {
                p.getInventory().addItem(new ItemStack(Material.SHULKER_SHELL, 2));
                sendChat(p, "&eShulker shells have appeared in your inventory.");
            }
            if (d == 395) {
                p.getInventory().addItem(new ItemStack(Material.DRAGON_EGG));
                sendChat(p, "&eA dragon egg has appeared in your inventory.");
            }
        }
    }
}
