package me.mrarcane.crispycore.listeners;

import me.mrarcane.crispycore.inventories.HomeInventory;
import me.mrarcane.crispycore.inventories.IconsInventory;
import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.ItemStack;

import java.util.HashMap;
import java.util.Set;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 3/6/2019
 **/
public class InventoryClickListener implements Listener {
    public static HashMap<Player, String> homeMap = new HashMap<>();

    @EventHandler
    private void onClick(InventoryClickEvent e) {
        ItemStack clicked = e.getCurrentItem();
        Player p = (Player) e.getWhoClicked();
        //Home icons
        if (e.getView().getTitle().equals("Select your home icon")) {
            PlayerManager pd = new PlayerManager(p.getUniqueId().toString());
            e.setCancelled(true);
            if (clicked == null) {
                return;
            }
            //Set your home icon
            ConfigurationSection homeData = pd.getConfigurationSection("Home data." + homeMap.get(p));
            homeData.set("Icon", clicked.getType().toString());
            pd.save();
            sendChat(p, "&6Home icon set to: &7" + clicked.getItemMeta().getDisplayName());
            new HomeInventory(p);
        }
        //Homes
        if (e.getView().getTitle().equals("Homes")) {
            e.setCancelled(true);
            if (clicked == null) {
                return;
            }
            //Check if right click and move to the Icons inventory
            if (e.getClick().isRightClick()) {
                homeMap.put(p, clicked.getItemMeta().getDisplayName());
                new IconsInventory(p);
                return;
            }
            PlayerManager pd = new PlayerManager(p.getUniqueId().toString());
            Set<String> hdSection = pd.getConfigurationSection("Home data").getKeys(false);
            for (String home : hdSection) {
                String itemName = clicked.getItemMeta().getDisplayName();
                ConfigurationSection homeData = pd.getConfigurationSection("Home data." + itemName);
                double x = homeData.getDouble("x");
                double y = homeData.getDouble("y");
                double z = homeData.getDouble("z");
                Location loc = new Location(Bukkit.getWorld(homeData.getString("w")), x, y, z);
                if (itemName.equals(home)) {
                    p.teleport(loc);
                    sendChat(p, String.format("&7Teleporting to %s", clicked.getItemMeta().getDisplayName()));
                }
                
            }
        }
    }
}
