package me.mrarcane.crispycore.listeners;

import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

/**
 * File generated by: MrArcane
 * 6/3/2019
 **/
public class PlayerInteractListener implements Listener {

    @EventHandler
    private static void onBlockClick(org.bukkit.event.player.PlayerInteractEvent e) {
    /*    Player p = e.getPlayer();
        ItemStack i = p.getInventory().getItemInMainHand();
        Block b = e.getClickedBlock();
        Material wShovel = Material.WOODEN_SHOVEL;
        Material sShovel = Material.STONE_SHOVEL;
        Material iShovel = Material.IRON_SHOVEL;
        Material gShovel = Material.GOLDEN_SHOVEL;
        Material dShovel = Material.DIAMOND_SHOVEL;
        assert b != null;
        //Path to Grass

        if (b.getType() == Material.GRASS_PATH && e.getAction() == Action.RIGHT_CLICK_BLOCK) {
            if (i.getType() == wShovel || i.getType() == sShovel || i.getType() == iShovel  || i.getType() == gShovel || i.getType() == dShovel) {
                b.setType(Material.GRASS_BLOCK);
            }
            return;
        }
    }
    @EventHandler
    private void onBlockBreak(BlockBreakEvent e) {
        if (e.getBlock().getType().equals(Material.GRASS_PATH)) {
            Player p = e.getPlayer();
            ItemStack i = p.getInventory().getItemInMainHand();
            if (i.containsEnchantment(Enchantment.SILK_TOUCH)) {
                e.getBlock().setType(Material.AIR);
                e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(), new ItemStack(Material.GRASS_PATH));
            }
        }*/
    }
}
