package me.mrarcane.crispycore.listeners;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

import java.io.File;

import static me.mrarcane.crispycore.commands.TpaCommand.tpmap;
import static me.mrarcane.crispycore.commands.TpaHereCommand.tpheremap;
import static me.mrarcane.crispycore.managers.CoordinatesManager.coordsMap;
import static me.mrarcane.crispycore.utils.ChatUtil.color;
import static me.mrarcane.crispycore.utils.ChatUtil.log;

/**
 * File generated by: MrArcane
 * 1/6/2018
 **/
public class PlayerQuitListener implements Listener {

    @EventHandler
    private void onQuit(final org.bukkit.event.player.PlayerQuitEvent e) {
        org.bukkit.entity.Player p = e.getPlayer();
        PlayerManager pd = new PlayerManager(p.getUniqueId().toString());
        File data = new File(Main.getInstance().getDataFolder() + "/Players/", p.getUniqueId() + ".yml");
        World w = Bukkit.getWorld("world");
        if (!data.exists()) {
            pd.createSection("Player");
            ConfigurationSection pSection = pd.getConfigurationSection("Player");
            ;
            pSection.set("Max homes", 1);
            pSection.set("Homes", 0);
            pd.save();
        }
        Location loc = p.getLocation();
        ConfigurationSection pFile = pd.getConfigurationSection("Player");
        pFile.set("Time", System.currentTimeMillis());
        pFile.set("x", loc.getBlockX());
        pFile.set("y", loc.getBlockY());
        pFile.set("z", loc.getBlockZ());
        pFile.set("world", loc.getWorld().getName());
        pd.save();
        e.setQuitMessage(color(String.format("&e%s &ehas left the building.", p.getDisplayName())));
        if (tpmap.containsKey(p)) {
            tpmap.remove(p);
        }
        if (tpheremap.containsKey(p)) {
            tpheremap.remove(p);
        }
        if (coordsMap.containsKey(p)) {
            coordsMap.remove(p);
            if (Main.debug()) {
                log(String.format("Removed %s from coordinates map!", p.getDisplayName()));
            }
        }
    }
}
