package me.mrarcane.crispycore.listeners;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.Location;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

import java.io.File;

import static me.mrarcane.crispycore.commands.ConsentCommand.bypassConsentMap;
import static me.mrarcane.crispycore.commands.ConsentCommand.consentMap;
import static me.mrarcane.crispycore.commands.MessageCommand.pmMap;
import static me.mrarcane.crispycore.commands.TpaCommand.tpmap;
import static me.mrarcane.crispycore.commands.TpaHereCommand.tpheremap;
import static me.mrarcane.crispycore.listeners.PlayerJoinListener.prefixMap;
import static me.mrarcane.crispycore.managers.CoordinatesManager.coordsMap;
import static me.mrarcane.crispycore.utils.ChatUtil.color;
import static me.mrarcane.crispycore.utils.ChatUtil.log;

/**
 * File generated by: MrArcane
 * 1/6/2018
 **/
public class PlayerQuitListener implements Listener {

    @EventHandler
    private void onQuit(final PlayerQuitEvent e) {
        Player p = e.getPlayer();
        PlayerManager pd = new PlayerManager(p.getUniqueId().toString());
        Location loc = p.getLocation();
        ConfigurationSection pFile = pd.getConfigurationSection("Player");
        pFile.set("Time", System.currentTimeMillis());
        pFile.set("x", loc.getBlockX());
        pFile.set("y", loc.getBlockY());
        pFile.set("z", loc.getBlockZ());
        pFile.set("world", loc.getWorld().getName());
        pd.save();
        e.setQuitMessage(color(String.format("&e%s &ehas left the building.", p.getDisplayName())));
        bypassConsentMap.remove(p);
        prefixMap.remove(p);
        tpmap.remove(p);
        tpheremap.remove(p);
        pmMap.remove(p);
        consentMap.remove(p);
        if (coordsMap.containsKey(p)) {
            coordsMap.remove(p);
            if (Main.debug()) {
                log(String.format("Removed %s from coordinates map!", p.getDisplayName()));
            }
        }
    }
}
