package me.mrarcane.crispycore.listeners;

import me.mrarcane.crispycore.enums.ItemNames;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerItemBreakEvent;
import org.bukkit.event.player.PlayerItemDamageEvent;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

import static me.mrarcane.crispycore.utils.ChatUtil.sendAction;

/**
 * File generated by: MrArcane
 * 2/9/2019
 **/
public class PlayerItemListener implements Listener {
    private String itemName(Material type) {
        return ItemNames.valueOf(type.toString()).firstAllUpperCased();
    }

    @EventHandler
    private void BlockBreak(PlayerItemDamageEvent e) {
        Player p = e.getPlayer();
        ItemStack i = e.getItem();
        ArrayList<Integer> l = new ArrayList<>();
        l.add(5);
        l.add(10);
        l.add(15);
        l.add(20);
        l.add(25);
        for (int u : l) {
            int uses = i.getType().getMaxDurability() - u;
            if (i.getDurability() == uses) {
                sendAction(p, String.format("&c&l%s is almost broken!", itemName(i.getType())));
            }
        }
    }
    @EventHandler
    private void onBreak(PlayerItemBreakEvent e) {
        Player p = e.getPlayer();
        Material i = e.getBrokenItem().getType();
        p.spawnParticle(org.bukkit.Particle.FLAME, p.getLocation(), 100, 2.0D, 2.0D, 2.0D, 2.0D);
        sendAction(p, String.format("&c&lYour &7&l%s &c&lshattered!", itemName(i)));
    }
}
