package me.mrarcane.crispycore.listeners;

import me.mrarcane.crispycore.Main;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.AsyncPlayerChatEvent;
import org.bukkit.event.player.PlayerCommandPreprocessEvent;

import java.util.List;
import java.util.Random;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/9/2019
 **/
public class PlayerChatListener implements Listener {

    @EventHandler
    private void onChat(AsyncPlayerChatEvent e) {
        String msg = e.getMessage().toLowerCase();
        String nmsg;
        Random r = new Random();
        List<String> words = Main.getInstance().getConfig().getStringList("Chat replacement.Words");
        List<String> list = Main.getInstance().getConfig().getStringList("Chat replacement.List");
        for (String w : words) {
            if (msg.contains(w)) {
                nmsg = msg.replace(w, list.get(r.nextInt(list.size())));
                e.setMessage(nmsg);
            }
        }
    }

    public boolean isDisabled(String cmd) {
        switch (cmd.toLowerCase()) {
            case "/version":
            case "/ver":
            case "/pl":
            case "/plugins":
            case "/?":
                return true;
        }

        return false;
    }

    @EventHandler
    private void disableSpecific(PlayerCommandPreprocessEvent e) {
        Player p = e.getPlayer();
        if (!p.hasPermission("crispycore.commands") && isDisabled(e.getMessage())) {
            e.setCancelled(true);
            e.isCancelled();
            sendChat(p, "&cThat command is disabled");
        }
        if (!p.hasPermission("crispycore.commands") && e.getMessage().split("\\s")[0].contains(":")) {
            e.setCancelled(true);
            e.isCancelled();
            sendChat(p, "&cYou cannot use plugin specific commands!");
        }
    }
}
