package me.mrarcane.crispycore.listeners;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.managers.AnnouncementManager;
import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.*;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;

import static me.mrarcane.crispycore.managers.PlayerManager.*;
import static me.mrarcane.crispycore.utils.ChatUtil.*;
import static me.mrarcane.crispycore.utils.FileUtil.cfg;

/**
 * File generated by: MrArcane
 * 11/7/2017
 **/
public class PlayerJoinListener implements Listener {

    public static HashMap<OfflinePlayer, String> prefixMap = new HashMap<>();
    @EventHandler
    private void onJoin(final PlayerJoinEvent e) {
        Player p = e.getPlayer();
        PlayerManager pm = new PlayerManager(p.getUniqueId().toString());
        //Check if player needs data.
        pm.loadData(p);
        if (!p.hasPlayedBefore()) {
            broadcast(cfg.getConfigurationSection("New join").getString("Announcement").replace("{player}", p.getName()));
            //Check for the spawn
            if (cfg.getConfigurationSection("Spawn") != null) {
                ConfigurationSection s = cfg.getConfigurationSection("Spawn");
                p.teleport(new Location(Bukkit.getWorld(s.getString("w")), s.getDouble("x"), s.getDouble("y"), s.getDouble("z")));
            }
        }
        if (pm.contains("Player.Join message")) {
            e.setJoinMessage(ChatColor.YELLOW + pm.getString("Player.Join message"));
        } else {
            e.setJoinMessage(color("&e" + p.getDisplayName() + " &ehas entered the building."));
        }

        //Checks for a prefix in Player data
        if (pm.contains("Player.Prefix")) {
            prefixMap.put(p, pm.getString("Player.Prefix"));
        }

        getGroup(p);
        getMail(p);

        //Message of the day (Needs work)
        try {
            File motd = new File(Main.getInstance().getDataFolder(), "motd.txt");
            BufferedReader br = new BufferedReader(new FileReader(motd));
            String line;
            while ((line = br.readLine()) != null) {
                sendChat(p, line.replace("{player}", p.getDisplayName()));
            }
        } catch (IOException f) {
            f.printStackTrace();
        }
        if (Bukkit.getOnlinePlayers().size() > 0) {
            AnnouncementManager.restart(Main.getInstance());
        }
    }
}