package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.managers.AnnouncementManager;
import me.mrarcane.crispycore.utils.FileUtil;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

import java.util.List;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 1/9/2018
 **/
public class AutoBroadcastCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        FileUtil file = new FileUtil(null, "Announcements");
        List<String> msgSection = file.getStringList("Messages");
        //Check for /autobroadcast
        if (args.length == 0) {
            sendChat(sender, "&cUsage: /autobroadcast <add/delete/list>");
            return true;
        }

        //Check if args is add
        if (args[0].equalsIgnoreCase("add")) {
            if (args.length == 1) {
                sendChat(sender, "&cUsage: /autobroadcast add <message>");
                return true;
            }

            String msg = "";
            for (int i = 1; i < args.length; i++) {
                msg = msg + " " + args[i];
            }
            msgSection.add(msg.trim());
            file.set("Messages", msgSection);
            sendChat(sender, String.format("&aCreated broadcast &7'&f%s&7'", msg.trim()));
            file.save();
            AnnouncementManager.restart(Main.getInstance());
            return true;
        }

        //Check if args is delete
        if (args[0].equalsIgnoreCase("delete") || args[0].equalsIgnoreCase("del")) {
            if (args.length == 1) {
                sendChat(sender, "&cUsage: /autobroadcast <delete/del> <int>");
                return true;
            }
            int i = Integer.parseInt(args[1]) - 1;
            if (msgSection.size() < 1) {
                sendChat(sender, "&cThere are no messages defined.");
                return true;
            }
            if (i > msgSection.size()) {
                sendChat(sender, "&cError! That broadcast doesn't exist.");
                return true;
            }
            sendChat(sender, String.format("&aRemoved broadcast &7'&f%s&7'", msgSection.get(i)));
            msgSection.remove(msgSection.get(i));
            file.set("Messages", msgSection);
            file.save();
            AnnouncementManager.restart(Main.getInstance());
            return true;
        }

        //Check if args is list
        if (args[0].equalsIgnoreCase("list")) {
            for (int i = 0; i < msgSection.size(); i++) {
                sendChat(sender, String.format("&7%s. &a%s", i + 1, msgSection.get(i)));
            }
            return true;
        }

        //Invaild command
        sendChat(sender, "&cInvalid command.");
        sendChat(sender, "&cUsage: /autobroadcast <add/delete/list>");
        return false;
    }
}
