package me.mrarcane.crispycore.commands;

import org.bukkit.Bukkit;
import org.bukkit.Sound;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.utils.ChatUtil.broadcast;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/10/2019
 **/
public class CrispCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            if (args.length == 0) {
                sendChat(p, "&cUsage /crisp <player>");
                return true;
            }

            if (args[0] == null) {
                sendChat(p, String.format("&c%s was not found.", args[0]));
                return true;
            }

            Player t = Bukkit.getPlayer(args[0]);
            if (t == p) {
                sendChat(p, "&cSelf harm is bad!");
                return true;
            }

            //Bukkit.getServer().getWorld(t.getWorld().getName()).getBlockAt(t.getLocation()).getRelative(BlockFace.UP).setType(Material.FIRE);
            t.setFireTicks(20);
            broadcast(String.format("&7%s &cshowed &7%s &chow to get crispy!", p.getName(), t.getName()));
            for (Player op : Bukkit.getOnlinePlayers()) {
                op.playSound(op.getLocation(), Sound.ENTITY_FIREWORK_ROCKET_TWINKLE, 10, 1);
            }

            return true;
        }

        return false;
    }
}
