package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.List;
import java.util.Random;

import static me.mrarcane.crispycore.utils.ChatUtil.log;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 6/27/2019
 **/
public class FeedCommand implements CommandExecutor {
    private Random r = new Random();
    private List<String> msgs = Main.getInstance().getConfig().getStringList("Feed messages");

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            Random r = new Random();
            List<String> msgs = Main.getInstance().getConfig().getStringList("Feed messages");
            if (args.length == 0) {
                p.setFoodLevel(20);
                sendChat(p, msgs.get(r.nextInt(msgs.size())));
                return true;
            }
            return true;
        }
        if (args.length == 0) {
            log("Usage: /feed <player>");
            return true;
        }
        if (args.length == 1) {
            Player p = Bukkit.getPlayer(args[0]);
            p.setFoodLevel(20);
            sendChat(p, msgs.get(r.nextInt(msgs.size())));
            log(String.format("You feed %s", p.getDisplayName()));
            return true;
        }
        return false;
    }
}
