package me.mrarcane.crispycore.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 8/5/2018
 **/
public class FlyCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String s, String[] args) {
        Player p = (Player) sender;
        if (p.getAllowFlight() == true) {
            p.setAllowFlight(false);
            p.setFlying(false);
            sendChat(p, "&eYou are no longer flying!");
            return true;
        }

        p.setAllowFlight(true);
        p.setFlying(true);
        sendChat(p, "&eYou are now flying!");
        return false;
    }
}
