package me.mrarcane.crispycore.commands;

import org.bukkit.Material;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.ArrayList;
import java.util.List;

import static me.mrarcane.crispycore.utils.ChatUtil.color;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/15/2019
 **/
public class FunItemCommand implements CommandExecutor {
    public static ItemStack trout = new ItemStack(Material.COD);
    public static ItemMeta stickMeta;

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            if (args.length == 0) {
                sendChat(p, "&cUsage: /funitem <item>");
                sendChat(p, "&eItems: &7Stick, Trout");
                return true;
            }

            if (args.length == 1) {
                if (args[0].equalsIgnoreCase("trout")) {
                    List<String> lore = new ArrayList<>();
                    lore.add(color("&d&lKnockback XXX"));
                    ItemMeta im = trout.getItemMeta();
                    assert im != null;
                    im.addItemFlags(ItemFlag.HIDE_ENCHANTS);
                    im.addEnchant(Enchantment.KNOCKBACK, 30, true);
                    im.setDisplayName(color("&eTrout of Destiny"));
                    im.setLore(lore);
                    trout.setItemMeta(im);
                    p.getInventory().addItem(trout);
                    return true;
                }

                if (args[0].equalsIgnoreCase("stick")) {
                    ItemStack stick = new ItemStack(Material.STICK);
                    List<String> lore = new ArrayList<>();
                    lore.add(color("&dTells the truth about the player"));
                    ItemMeta im = stick.getItemMeta();
                    assert im != null;
                    im.addItemFlags(ItemFlag.HIDE_ENCHANTS);
                    im.addEnchant(Enchantment.ARROW_DAMAGE, 30, true);
                    im.setDisplayName(color("&eStick of Truth"));
                    im.setLore(lore);
                    stick.setItemMeta(im);
                    p.getInventory().addItem(stick);
                    stickMeta = stick.getItemMeta();
                    return true;
                }

                sendChat(p, String.format("&c%s is not a correct fun item!", args[0]));
                return true;
            }
        }
        return false;
    }
}
