package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/5/2018
 **/
public class HatCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            ItemStack head = p.getInventory().getHelmet();
            ItemStack hand = p.getInventory().getItemInMainHand();
            if (args.length == 0) {
                if (p.getInventory().getItemInMainHand() == null) {
                    sendChat(p, "&cYou must be holding an item.");
                    return true;
                }
       /*         if (p.getInventory().getSize() >= 36) {
                    sendChat(p, "&cSorry, your inventory is full.");
                    return true;
                }*/
                if (head != null) {
                    Bukkit.getScheduler().scheduleSyncDelayedTask(Main.getInstance(), () -> {
                        p.getInventory().setHelmet(hand);
                        p.getInventory().removeItem(hand);
                        p.getInventory().addItem(head);
                        sendChat(p, "&eEnjoy your hat!");
                    }, 5);
                    return true;
                }
                p.getInventory().setHelmet(hand);
                p.getInventory().removeItem(hand);
                sendChat(p, "&eEnjoy your hat!");
                return true;
            }
            sendChat(p, "&cIncorrect command, try again.");
            return true;
        }
        return false;
    }
}
