package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.ConfigurationSection;

import java.util.Set;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 5/28/2018
 **/
public class HomeCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof org.bukkit.entity.Player) {
            org.bukkit.entity.Player p = (org.bukkit.entity.Player) sender;
            PlayerManager pd = new PlayerManager(p.getUniqueId().toString());
            ConfigurationSection hData = pd.getConfigurationSection("Home data");
            Set<String> h = pd.getConfigurationSection("Home data").getKeys(false);
            if (h.size() == 0) { //No homes found
                sendChat(p, "&cNo homes defined.");
                return true;
            }
            if (args.length == 0) { //If homes is zero
                if (h.size() == 1) {
                    for (String home : h) { //Loop through all the homes.
                        ConfigurationSection data = pd.getConfigurationSection("Home data").getConfigurationSection(home);
                        p.teleport(new Location(Bukkit.getWorld(data.getString("w")), data.getDouble("x"), data.getDouble("y"), data.getDouble("z")));
                        sendChat(p, String.format("&7Teleporting to %s", home));
                    }
                    return true;
                } else {
                    sendChat(p, "&cUsage: /home <home>");
                    return true;
                }
            }
            if (args.length == 1) { //If homes is greater than zero
                ConfigurationSection home = hData.getConfigurationSection(args[0].toLowerCase());
                if (home == null) {
                    sendChat(p, String.format("&cHome '&7%s&c' doesn't exist.", args[0].toLowerCase()));
                    return true;
                }
                p.teleport(new Location(Bukkit.getWorld(home.getString("w")), home.getDouble("x"), home.getDouble("y"), home.getDouble("z")));
                sendChat(p, String.format("&7Teleporting to %s", args[0].toLowerCase()));
                return true;
            }
        }
        return false;
    }
}
