package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.inventories.HomeInventory;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

/**
 * File generated by: MrArcane
 * 6/6/2018
 **/
public class HomesCommand implements CommandExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {

        if (sender instanceof Player) {
            Player p = (Player) sender;
            new HomeInventory(p);
        }
        return false;
    }

}
