package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 6/27/2019
 **/
public class JoinMessageCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        Player p = (Player) sender;
        PlayerManager user = new PlayerManager(p.getUniqueId().toString());
        String msg = "";
        for (String arg : args) {
            msg = msg + " " + arg;
        }
        if (!msg.contains(p.getDisplayName())) {
            sendChat(p, "&cYou must add your username to the join message!");
            return true;
        }
        if (msg.length() < 15) {
            sendChat(p, "&cJoin message must have at least &715 &ccharacters!");
            return true;
        }
        if (msg.length() >= 121) {
            sendChat(p, "&cJoin message can only allow 120 characters!");
            return true;
        }
        user.set("Player.Join message", msg.trim());
        user.save();
        sendChat(p, String.format("&aJoin message changed to: %s", msg.trim()));
        return false;
    }
}
