package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

import java.util.List;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 8/2/2018
 **/
public class LinksCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        List<String> l = Main.getInstance().getConfig().getStringList("Links");
        for (String s : l) {
            sendChat(sender, s);
        }
        return false;
    }
}
