package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.managers.PlayerManager;
import net.md_5.bungee.api.chat.ClickEvent;
import net.md_5.bungee.api.chat.ComponentBuilder;
import net.md_5.bungee.api.chat.HoverEvent;
import net.md_5.bungee.api.chat.TextComponent;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.io.File;
import java.util.List;

import static me.mrarcane.crispycore.managers.PlayerManager.getMail;
import static me.mrarcane.crispycore.utils.ChatUtil.color;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 1/15/2018
 **/
public class MailCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            PlayerManager pd = new PlayerManager(p.getUniqueId().toString());
            if (args.length == 0) {
                sendChat(p, "&cUsage: /mail <read/send/delete/clear>");
                return true;
            }
            if (args[0].equalsIgnoreCase("read")) {
                List<String> m = pd.getConfigurationSection("Player").getStringList("Mail");
                if (m.size() == 0) {
                    sendChat(p, "&6Mailbox is empty.");
                    return true;
                }
                sendChat(p, String.format("&6Inbox (&7%s&6):", m.size()));

                for (int i = 0; i < m.size(); i++) {
                    TextComponent msg = new TextComponent(color((i + 1) + ". " + m.get(i).trim()));
                    TextComponent a = new TextComponent(color(" &7[&cDelete&7]"));
                    a.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/mail delete " + (i + 1)));
                    a.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder(color("&6Click to delete message")).create()));
                    msg.addExtra(a);
                    p.spigot().sendMessage(msg);
                }
                return true;
            }
            if (args[0].equalsIgnoreCase("send")) {
                if (args.length <= 2) {
                    sendChat(p, "&cUsage: /mail send <player> <message>");
                    return true;
                }
                OfflinePlayer t = Bukkit.getOfflinePlayer(args[1]);
                if (t.isOnline()) {
                    getMail(p);
                }
                if (!t.hasPlayedBefore()) {
                    sendChat(p, String.format("&cCouldn't find %s.", args[1]));
                    return true;
                }
                File file = new File(Main.getInstance().getDataFolder() + "/Players/", t.getUniqueId().toString() + ".yml");
                PlayerManager td = new PlayerManager(t.getUniqueId().toString());
                if (td.getConfigurationSection("Player") == null) {
                    td.createSection("Player");
                    td.save();
                }
                StringBuilder sb = new StringBuilder();
                List<String> m = td.getConfigurationSection("Player").getStringList("Mail");
                String msg = "";
                for (int i = 2; i < args.length; i++) {
                    msg = String.valueOf(sb.append(args[i]).append(" "));
                }
                m.add(String.format("&e%s: &7%s", p.getName(), msg));
                td.getConfigurationSection("Player").set("Mail", m);
                td.save();
                sendChat(p, String.format("&6Message '&7%s&6' sent to &7%s", msg.trim(), t.getName()));
                return true;
            }
            if (args[0].equalsIgnoreCase("delete") || args[0].equalsIgnoreCase("del")) {
                if (args.length <= 1) {
                    sendChat(p, "&cUsage: /mail delete <int>");
                    return true;
                }
                List<String> m = pd.getConfigurationSection("Player").getStringList("Mail");
                int i = Integer.valueOf(args[1]) - 1;
                sendChat(p, "&6Message was deleted successfully.");
                m.remove(i);
                pd.getConfigurationSection("Player").set("Mail", m);
                pd.save();
                return true;
            }
            if (args[0].equalsIgnoreCase("clear")) {
                List<String> m = pd.getConfigurationSection("Player").getStringList("Mail");
                if (m.size() == 0) {
                    sendChat(p, "&cNo mail to clear.");
                    return true;
                }
                pd.getConfigurationSection("Player").set("Mail", null);
                pd.save();
                sendChat(p, "&6Inbox cleared.");
                return true;
            } else {
                sendChat(p, "&cIncorrect command, try again.");
            }
            return true;
        }
        return false;
    }
}