package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.ConfigurationSection;

import static me.mrarcane.crispycore.managers.PlayerManager.timePlayer;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 1/15/2018
 **/
public class SeenCommand implements CommandExecutor {
    private void playerHomes(CommandSender player, OfflinePlayer target) {
        PlayerManager user = new PlayerManager(target.getUniqueId().toString());
        if (player.hasPermission("crispycore.hometeleport")) {
            sendChat(player, "&eHomes: &7" + user.getConfigurationSection("Home data").getKeys(false).toString().replace("[", "").replace("]", "").replace(",", "&c,&7"));
            sendChat(player, "&aTo teleport to the players home type &7/hometeleport <player> <home>");
        }
    }

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (args.length == 0) {
            sendChat(sender, "&cUsage: /seen <player>");
            return true;
        }
        OfflinePlayer t = Bukkit.getOfflinePlayer(args[0]);
        PlayerManager user = new PlayerManager(t.getUniqueId().toString());
        ConfigurationSection pFile = user.getConfigurationSection("Player");
        ;

        if (!t.hasPlayedBefore()) {
            sendChat(sender, String.format("&c%s doesn't exist in our datebase.", t.getName()));
            return true;
        }
        if (t.isOnline()) {
            sendChat(sender, String.format("&eUsername: &7%s", t.getName()));
            assert pFile != null;
            sendChat(sender, String.format("&eOnline since: &7%s", timePlayer(pFile.getLong("Time"))));
            playerHomes(sender, t);
            return true;
        }
        if (pFile.getString("Last online") != null) {
            sendChat(sender, String.format("&eUsername: &7%s", t.getName()));
            sendChat(sender, String.format("&eLast seen: &7%s", timePlayer(pFile.getLong("Time"))));
            playerHomes(sender, t);
        } else {
            sendChat(sender, String.format("&eUsername: &7%s", t.getName()));
            sendChat(sender, String.format("&eLast seen: &7%s", timePlayer(pFile.getLong("Time"))));
            playerHomes(sender, t);
        }
        if (sender.hasPermission("crispycore.seen.location")) {
            sendChat(sender, String.format("&eLocation: &7%s&e, &7%s&e, &7%s&e, &7%s&e", pFile.getInt("x"), pFile.getInt("y"), pFile.getInt("z"), pFile.getString("world")));
        }
        return false;
    }
}
