package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.managers.PlayerManager;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.ConfigurationSection;

import java.util.Set;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 5/28/2018
 **/
public class SetHomeCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof org.bukkit.entity.Player) {
            org.bukkit.entity.Player p = (org.bukkit.entity.Player) sender;
            Location loc = p.getLocation();
            PlayerManager pd = new PlayerManager(p.getUniqueId().toString());
            ConfigurationSection pSection = pd.getConfigurationSection("Player");
            ;
            ConfigurationSection hSection = pd.getConfigurationSection("Home data");
            int aHomes = 0;
            int mHomes = 0;
            if (args.length != 1) {
                Set<String> h = pd.getConfigurationSection("Home data").getKeys(false);
                if (h.size() < 1) { //If we have no homes, set one.
                    pd.getConfigurationSection("Home data").createSection("home".toLowerCase());
                    hSection.getConfigurationSection("home").set("x", loc.getX());
                    hSection.getConfigurationSection("home").set("y", loc.getY());
                    hSection.getConfigurationSection("home").set("z", loc.getZ());
                    hSection.getConfigurationSection("home").set("w", loc.getWorld().getName());
                    aHomes++;
                    pSection.set("Homes", aHomes);
                    pd.save();
                    sendChat(p, "&7Home '&ahome&7' created.");
                    return true;
                }
                sendChat(p, "&cUsage: /sethome <name>");
            } else {
                if (pd.getConfigurationSection("Home data") == null) {
                    pd.createSection("Home data");
                    pSection.set("Homes", 0);
                    pSection.set("Max homes", 1);
                    pd.save();
                }
                if (pSection.getString("Homes") != null) {
                    aHomes = Integer.parseInt(pSection.getString("Homes"));
                }
                if (pSection.getString("Max homes") != null) {
                    mHomes = Integer.parseInt(pSection.getString("Max homes"));
                }
                Set<String> h = pd.getConfigurationSection("Home data").getKeys(false);
                for (String home : h) {
                    if (home.equalsIgnoreCase(args[0].toLowerCase())) {
                        hSection.getConfigurationSection(args[0].toLowerCase()).set("x", loc.getX());
                        hSection.getConfigurationSection(args[0].toLowerCase()).set("y", loc.getY());
                        hSection.getConfigurationSection(args[0].toLowerCase()).set("z", loc.getZ());
                        hSection.getConfigurationSection(args[0].toLowerCase()).set("w", loc.getWorld().getName());
                        sendChat(p, String.format("&7Home '&a%s&7' updated.", args[0].toLowerCase()));
                        pd.save();
                        return true;
                    }
                }
                if (aHomes == mHomes) {
                    sendChat(p, String.format("&cYou can only set &7%s &chomes.", mHomes));
                    return true;
                }
                if (pd.getConfigurationSection("Home data").getConfigurationSection(args[0]) == null) {
                    pd.getConfigurationSection("Home data").createSection(args[0].toLowerCase());
                    hSection.getConfigurationSection(args[0].toLowerCase()).set("x", loc.getX());
                    hSection.getConfigurationSection(args[0].toLowerCase()).set("y", loc.getY());
                    hSection.getConfigurationSection(args[0].toLowerCase()).set("z", loc.getZ());
                    hSection.getConfigurationSection(args[0].toLowerCase()).set("w", loc.getWorld().getName());
                    aHomes++;
                    pSection.set("Homes", aHomes);
                    pd.save();
                    sendChat(p, String.format("&7Home '&a%s&7' created.", args[0].toLowerCase()));
                    return true;
                }
            }
            return true;
        }
        return false;
    }
}
