package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 3/10/2018
 **/
public class SetSpawnCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        FileConfiguration cfg = Main.getInstance().getConfig();
        if (sender instanceof Player) {
            Player p = (Player) sender;
            Location loc = p.getLocation();
            if (cfg.getConfigurationSection("Spawn") == null) {
                cfg.createSection("Spawn");
            }
            if (args.length == 0) {
                cfg.getConfigurationSection("Spawn").set("x", loc.getX());
                cfg.getConfigurationSection("Spawn").set("y", loc.getY() + 1);
                cfg.getConfigurationSection("Spawn").set("z", loc.getZ());
                cfg.getConfigurationSection("Spawn").set("w", loc.getWorld().getName());
                Main.getInstance().saveConfig();
                sendChat(sender, "&aSpawn point set at your location!");
                return true;
            }
            return true;
        }
        return false;
    }
}
