package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 7/20/2018
 **/
public class SpawnCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        FileConfiguration cfg = Main.getInstance().getConfig();
        ConfigurationSection s = cfg.getConfigurationSection("Spawn");
        Player p = (Player) sender;
        if (s == null) {
            sendChat(p, "&cThere is no spawn set!");
            return true;
        }
        p.teleport(new Location(Bukkit.getWorld(s.getString("w")), s.getDouble("x"), s.getDouble("y"), s.getDouble("z")));
        sendChat(p, "&7Teleporting..");
        return false;
    }
}
