package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.hooks.Vault;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.List;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 3/10/2018
 **/
public class StaffCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        List<String> list = Main.getList("Staff list");
        ArrayList<String> players = new ArrayList<>();
        for (Player op : Bukkit.getOnlinePlayers()) {
            String group = Vault.permission.getPrimaryGroup(op);
            if (list.contains(group)) {
                char first = Character.toUpperCase(group.charAt(0));
                players.add(String.format("&e%s &7%s", first + group.substring(1), op.getDisplayName()));
            }
        }
        sendChat(sender, String.format("&eStaff online (&7%s&e):", players.size()));
        for (String result : players) {
            sendChat(sender, "&7" + result);
        }
        return false;
    }
}
