package me.mrarcane.crispycore.commands;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 8/19/2018
 **/
public class TeleportHereCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            if (args.length != 1) {
                sendChat(p, "&cUsage: /teleporthere <player>");
                return true;
            }
            Player t = Bukkit.getPlayer(args[0]);
            if (t == null) {
                sendChat(p, "&cPlayer is not online!");
                return true;
            }
            if (t == p) {
                sendChat(p, "&cYou cannot teleport to yourself.");
                return true;
            }
            t.teleport(p);
            sendChat(p, String.format("&eTeleporting &7%s &eto your location.", t.getName()));
            sendChat(t, String.format("&cYou're being teleported to &l&7%s's &clocation.", p.getName()));
            return true;
        }
        sendChat(Bukkit.getConsoleSender(), "&cYou must be a player to do this.");
        return false;
    }
}
