package me.mrarcane.crispycore.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 6/27/2019
 **/
public class TopCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (args.length == 0) {
            Player p = (Player) sender;
            if (p.getWorld().getHighestBlockAt(p.getLocation()).getLocation().add(0, 1, 0) == null) {
                sendChat(p, "&cThere is no block above you.");
                return true;
            }
            p.teleport(p.getWorld().getHighestBlockAt(p.getLocation()).getLocation().add(0, 1, 0));
            sendChat(p, "&aYou've been teleported to the top.");
        }
        return false;
    }
}
