package me.mrarcane.crispycore.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.commands.BackCommand.back;
import static me.mrarcane.crispycore.commands.TpaCommand.tpmap;
import static me.mrarcane.crispycore.commands.TpaHereCommand.tpheremap;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/8/2019
 **/
public class TpaAcceptCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String value, String[] ags) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            if (tpheremap.containsKey(p)) {
                p.teleport(tpheremap.get(p));
                sendChat(tpheremap.get(p), String.format("&7%s &ahas teleported to you.", p.getName()));
                sendChat(p, String.format("&aYou have telpeorted to &7%s.", tpheremap.get(p).getName()));
                tpheremap.remove(p);
                return true;
            }
            if (tpmap.containsKey(p)) {
                if (p.hasPermission("crispycore.back")) {
                    back.put(p, p.getLocation());
                    sendChat(p, "&eTo go back type &7/back");
                }
                tpmap.get(p).teleport(p);
                sendChat(tpmap.get(p), String.format("&aYou teleported to &7%s.", p.getName()));
                sendChat(p, String.format("&7%s &ahas teleported to your location.", tpmap.get(p).getName()));
                tpmap.remove(p);
                return true;
            }
            sendChat(p, "&cNo teleport requests found.");
                return true;
        }
        return false;
    }
}
