package me.mrarcane.crispycore.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.crispycore.commands.TpaCommand.tpmap;
import static me.mrarcane.crispycore.commands.TpaHereCommand.tpheremap;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/8/2019
 **/
public class TpaDenyCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String value, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            if (tpheremap.containsKey(p)) {
                sendChat(tpheremap.get(p), "&cTeleport request denied.");
                sendChat(p, "&aTeleport request denied.");
                tpheremap.remove(p);
                return true;
            }
            if (tpmap.containsKey(p)) {
                sendChat(tpmap.get(p), "&cTeleport request denied.");
                sendChat(p, "&aTeleport request denied.");
                tpmap.remove(p);
                return true;
            }
            sendChat(p, "&cNo teleport requests found.");
            return true;
        }
        return false;
    }
}
