package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import me.mrarcane.crispycore.managers.PlayerManager;
import net.md_5.bungee.api.chat.ClickEvent;
import net.md_5.bungee.api.chat.ComponentBuilder;
import net.md_5.bungee.api.chat.HoverEvent;
import net.md_5.bungee.api.chat.TextComponent;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

import java.util.HashMap;
import java.util.Map;

import static me.mrarcane.crispycore.utils.ChatUtil.color;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 2/10/2019
 **/
public class TpaHereCommand implements CommandExecutor {

    public static Map<org.bukkit.entity.Player, org.bukkit.entity.Player> tpheremap = new HashMap<>();

    public boolean onCommand(CommandSender sender, Command cmd, String value, String[] args) {
        if (sender instanceof org.bukkit.entity.Player) {
            org.bukkit.entity.Player p = (org.bukkit.entity.Player) sender;
            if (args.length == 0) {
                sender.sendMessage(color("&7Usage: &c/tpahere <player>"));
                return false;
            }
            org.bukkit.entity.Player t = Bukkit.getPlayer(args[0]);
            if (p == t) {
                sendChat(p, "&cYou can't teleport to yourself!");
                return true;
            }
            if (t == null) {
                sendChat(p, String.format("&c%s is offline", args[0]));
                return true;
            }
            PlayerManager td = new PlayerManager(t.getUniqueId().toString());
            if (td.getString("Player.Teleport toggle").equals("false")) {
                sendChat(p, "&cThis player has teleporting disabled.");
                return true;
            }
            TextComponent msg = new TextComponent(color(String.format("&7%s &ais requesting you to teleport to them. ", p.getDisplayName())));
            TextComponent a = new TextComponent(color("&7[Accept] &aor &7"));
            TextComponent d = new TextComponent(color("&7[Deny]"));
            a.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/tpaccept"));
            a.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder("Click to accept!").create()));
            d.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/tpadeny"));
            d.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder("Click to deny!").create()));
            msg.addExtra(a);
            msg.addExtra(d);
            tpheremap.put(t, p);
            sendChat(p, String.format("&aRequesting to teleport &7%s &ato your location", t.getName()));
            t.spigot().sendMessage(msg);
            sendChat(t, "&aYou can disable this functionality by typing &7/tpa toggle");
            //Timer to cancel request
            Bukkit.getScheduler().scheduleSyncDelayedTask(Main.getInstance(), () -> {
                tpheremap.remove(t);
                if (tpheremap.containsKey(p)) {
                    sendChat(p, "&cTeleport request canceled!");
                }
            }, 600);
        }
        return false;
    }
}
