package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.Random;

import static java.lang.Math.abs;
import static me.mrarcane.crispycore.utils.ChatUtil.log;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 6/27/2019
 **/
public class WildCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            World w = Bukkit.getWorld("world");
            int minX = 0;
            int minZ = 0;
            int maxX = 0;
            int maxZ = 0;
            int x = 0;
            int y = 0;
            int z = 0;
            Location loc = null;
            int maxConfig = Main.getInstance().getConfig().getInt("Settings.Max wild");
            do {
                Random r = new Random();
                minX = 0 - maxConfig;
                minZ = 0 - maxConfig;
                maxX = maxConfig;
                maxZ = maxConfig;
                x = r.nextInt(maxX + 1 - minX) + minX;
                z = r.nextInt(maxZ + 1 - minZ) + minZ;
                y = w.getHighestBlockYAt(x, z) + 3;
                loc = new Location(w, x, y, z);
            } while ((abs(x) < 20000) && (abs(z) < 20000));
            p.teleport(loc);
            sendChat(p, "&aCrispy farted you into a random direction!");
            return true;
        }
        log("You must be a player to do this!");
        return true;
    }
}
