package me.mrarcane.crispycore.commands;

import me.mrarcane.crispycore.Main;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.Random;

import static me.mrarcane.crispycore.utils.ChatUtil.log;
import static me.mrarcane.crispycore.utils.ChatUtil.sendChat;

/**
 * File generated by: MrArcane
 * 6/27/2019
 **/
public class WildCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            World w = Bukkit.getWorld("world");
            int minX, minZ, maxX, maxZ, x, y, z = 0;
            Location loc;
            int maxConfig = Main.getInstance().getConfig().getInt("Settings.Max wild");
            Random r = new Random();
            minX = -maxConfig;
            minZ = -maxConfig;
            maxX = maxConfig;
            maxZ = maxConfig;
            x = r.nextInt(maxX + 1 - minX) + minX;
            z = r.nextInt(maxZ + 1 - minZ) + minZ;
            assert w != null;
            y = w.getHighestBlockYAt(x, z) + 3;
            loc = new Location(w, x, y, z);
            p.teleport(loc);
            sendChat(p, "&aCrispy farted you into a random direction!");
            return true;
        }
        log("You must be a player to do this!");
        return true;
    }
}
