package me.mrarcane.crispycore.utils;

import net.md_5.bungee.api.ChatColor;
import net.md_5.bungee.api.chat.ClickEvent;
import net.md_5.bungee.api.chat.ComponentBuilder;
import net.md_5.bungee.api.chat.HoverEvent;
import net.md_5.bungee.api.chat.TextComponent;
import org.bukkit.Bukkit;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * File generated by: MrArcane
 * 11/7/2017
 **/
public class ChatUtil {

    private static final Pattern pattern = Pattern.compile("#[a-fA-F0-9]{6}");

    public static String color(String in) {
          //Hex colors
          Matcher match = pattern.matcher(in);
          while (match.find()) {
              String color = in.substring(match.start(), match.end());
              in = in.replace(color, ChatColor.of(color) + "");
              match = pattern.matcher(in);
          }
          return ChatColor.translateAlternateColorCodes('&', in + "&f");
    }
    public static void sendAction(Player p, String text) {
        p.spigot().sendMessage(net.md_5.bungee.api.ChatMessageType.ACTION_BAR, TextComponent.fromLegacyText(color(text)));
    }

    public static void sendChat(CommandSender p, String msg) {
        p.sendMessage(color(msg));
    }

    public static void broadcast(String msg) {
        Bukkit.getServer().broadcastMessage(color(msg));
    }

    public static void log(String msg) {
        Bukkit.getConsoleSender().sendMessage(color("[CrispyCore] " + msg));
    }

    public static void sendClickableChat(Player p, String message, String hoverText, String command, ClickEvent.Action action) {
        TextComponent txtcomponent = new TextComponent(color(message));
        txtcomponent.setClickEvent(new ClickEvent(action, command));
        txtcomponent.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder(color(hoverText)).create()));
        p.spigot().sendMessage(txtcomponent);
    }

}
